### ISSUE TITLE
Sovereign Tech Fund: Fellowship for Maintainers

### ISSUE THREAD

**Issue by bebuch** [pnggroup/libpng#574]
@ctruta The German government wants to provide financial support for maintainers of open source projects from the end of the year. This may be of interest to you. (I'm not involved, just happened to see it on the news). libpng is essential for many of the projects that have been supported previously.

https://www.sovereigntechfund.de/news/introducing-the-fellowship-for-maintainers

> We're planning to start accepting fellowship applications by the end of Q3 2024, with selected maintainers beginning their fellowships in Q4.

**Comment by ctruta** [comment]
Thanks, @bebuch, you're very kind for letting me know. I could not have applied any earlier, because of a bunch of rather peculiar reasons, and now it's too late.

Quoting a friend of mine: _"I do the work for free but I get paid for the meetings"_. Considering how this project has no meetings, and how I don't mind doing the work for free anyway, I think I'm good 👍

I will see where the future takes me, and I will keep this opportunity in mind, also. Danke schön!
