### ISSUE TITLE
Using ZSTD for compression in PNG

### ISSUE THREAD

**Issue by birdie-github** [pnggroup/libpng#586]
(I sent this to png-mng-misc AT lists.sourceforge.net, Fri, 28 Apr 2023 11:51:14 +0000) but it never arrived, so let's try it here).

Hi,

I know the PNG standard is now set in stone and it's highly unlikely it's going to incorporate new compressions schemes but what about drafting a new lossless compression standard with a new extension, let's say, PNGZ, which is going to use Zstandard?

ZSTD has shown quite significant improvements over Zlib used in PNG to the tune of 40%.

Best regards,
Artem

**Comment by ProgramMax** [comment]
You probably want to post this in the PNG standard GitHub, rather than here.
Good news: [it is already being considered for future editions of PNG](https://github.com/w3c/png/issues/39).

There isn't a clear path forward on it. It will take some discussion.
On one hand, it is important not to break backwards compatibility. Existing decoders should continue to work. One possible solution here is to have a low rez copy of the image using old compression. But that doesn't seem great.
Another option is a new format like .png2 like you said.

**Comment by birdie-github** [comment]
Great to know such an idea/proposal already exists. Sorry for the noise then!
